id = "flow-theme"
name = "Flow Theme"
version = "1.1.0"
schema_version = 1
authors = ["Ric's Dev <ricdev.io@gmail.com>"]
description = "Flow Theme for Zed"
repository = "https://github.com/Rics-Dev/zed-flow-theme"
